version: '2'
services:
  lb:
    image: dockercloud/haproxy
    ports:
      - "80:80"
    links:
      - nodeapp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nodeapp:
    build: .
    env_file: env
  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data